global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Application
  - job_name: 'shopcuathuy-backend'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 5s

  # MySQL Database
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
